ubuntu@ip-172-31-95-46:~/microservice-kube_udacity_lab$ ./run_kubernetes.sh 
error: failed to create deployment: deployments.apps "py-helloworld-kube" already exists
NAME                                 READY   STATUS    RESTARTS   AGE
py-helloworld-kube-7c657fc4b-lvqpt   1/1     Running   0          2m57s
Forwarding from 0.0.0.0:8000 -> 80
Handling connection for 8000
ubuntu@ip-172-31-95-46:~/microservice-kube_udacity_lab$ ./make_prediction.sh 
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}
ubuntu@ip-172-31-95-46:~/microservice-kube_udacity_lab$ kubectl logs pod/py-helloworld-kube-7c657fc4b-lvqpt
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 124-524-500
[2023-07-13 18:26:24,174] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-07-13 18:26:24,179] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-07-13 18:26:24,207] INFO in app: Scaling Payload: 
{payload}
[2023-07-13 18:26:24,219] INFO in app: Output Prediction: 
[20.35373177134412]
127.0.0.1 - - [13/Jul/2023 18:26:24] "POST /predict HTTP/1.1" 200 -
